controller:
  extraArgs:
    default-ssl-certificate: ${default_tls_certificate}
  kind: DaemonSet
  ingressClassResource:
    name: ${class_resource_name}
    controllerValue: ${controller_value}
  service:
    loadBalancerIP: ${load_balancer_ip}
    annotations:
      # https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/#loadbalancer-annotations
      service.beta.kubernetes.io/azure-load-balancer-resource-group: ${load_balancer_resource_group}
